// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: tachibanapb/tachibana.proto

package tachibanapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TachibanaServiceClient is the client API for TachibanaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TachibanaServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type tachibanaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTachibanaServiceClient(cc grpc.ClientConnInterface) TachibanaServiceClient {
	return &tachibanaServiceClient{cc}
}

func (c *tachibanaServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/tachibanapb.TachibanaService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TachibanaServiceServer is the server API for TachibanaService service.
// All implementations must embed UnimplementedTachibanaServiceServer
// for forward compatibility
type TachibanaServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedTachibanaServiceServer()
}

// UnimplementedTachibanaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTachibanaServiceServer struct {
}

func (UnimplementedTachibanaServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedTachibanaServiceServer) mustEmbedUnimplementedTachibanaServiceServer() {}

// UnsafeTachibanaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TachibanaServiceServer will
// result in compilation errors.
type UnsafeTachibanaServiceServer interface {
	mustEmbedUnimplementedTachibanaServiceServer()
}

func RegisterTachibanaServiceServer(s grpc.ServiceRegistrar, srv TachibanaServiceServer) {
	s.RegisterService(&TachibanaService_ServiceDesc, srv)
}

func _TachibanaService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TachibanaServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tachibanapb.TachibanaService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TachibanaServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TachibanaService_ServiceDesc is the grpc.ServiceDesc for TachibanaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TachibanaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tachibanapb.TachibanaService",
	HandlerType: (*TachibanaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _TachibanaService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tachibanapb/tachibana.proto",
}
